"""
Django settings for E_learning project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")



SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-@6zdb&f0f&@$7_z5faa6=4eep@_(a1!c$ylxk_$1fkgd72$$7('
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'false'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,.onrender.com'
    ).split(',')
    if host.strip()
]

render_hostname = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_hostname and render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_hostname)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

if render_hostname:
    render_origin = f"https://{render_hostname}"
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'core',
    'courses',
    'accounts',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'E_learning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'E_learning.wsgi.application'



DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
if not DATABASE_URL:
    raise ImproperlyConfigured(
        "DATABASE_URL is not set. This project requires PostgreSQL "
        "(SQLite is no longer supported).\n"
        "Locally, add to .env:\n"
        "  DATABASE_URL=postgresql://postgres:<password>"
        "@127.0.0.1:5432/elearning\n"
        "On Render, set DATABASE_URL from your Postgres instance "
        "(service -> Environment)."
    )
if not DATABASE_URL.startswith(("postgres://", "postgresql://")):
    raise ImproperlyConfigured(
        "DATABASE_URL must be a PostgreSQL URL starting with "
        f"postgresql:// (got scheme {DATABASE_URL.split(':', 1)[0]!r}). "
        "SQLite is no longer supported."
    )

DATABASES = {
    'default': dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    ),
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CONSOLE_EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
SMTP_EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
BREVO_EMAIL_BACKEND = "core.mail_backends.BrevoAPIBackend"
CHAIN_EMAIL_BACKEND = "core.mail_backends.FallbackEmailBackend"

EMAIL_HOST = (os.environ.get("EMAIL_HOST") or "localhost").strip()
EMAIL_PORT = int((os.environ.get("EMAIL_PORT") or "587").strip())
EMAIL_HOST_USER = (os.environ.get("EMAIL_HOST_USER") or "").strip()
EMAIL_HOST_PASSWORD = (os.environ.get("EMAIL_HOST_PASSWORD") or "").strip()
EMAIL_USE_TLS = (
    (os.environ.get("EMAIL_USE_TLS") or "true").strip().lower() == "true"
)
EMAIL_TIMEOUT = int((os.environ.get("EMAIL_TIMEOUT") or "15").strip())
DEFAULT_FROM_EMAIL = (
    (os.environ.get("DEFAULT_FROM_EMAIL") or "").strip()
    or EMAIL_HOST_USER
    or "E-Learning <noreply@example.com>"
)

BREVO_API_KEY = (os.environ.get("BREVO_API_KEY") or "").strip()

_smtp_configured = bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)

EMAIL_BACKEND_CHAIN = []
if BREVO_API_KEY:
    EMAIL_BACKEND_CHAIN.append(BREVO_EMAIL_BACKEND)
if _smtp_configured:
    EMAIL_BACKEND_CHAIN.append(SMTP_EMAIL_BACKEND)
EMAIL_BACKEND_CHAIN.append(CONSOLE_EMAIL_BACKEND)

EMAIL_BACKEND = (os.environ.get("EMAIL_BACKEND") or "").strip()
if not EMAIL_BACKEND:
    EMAIL_BACKEND = (
        CHAIN_EMAIL_BACKEND
        if len(EMAIL_BACKEND_CHAIN) > 1
        else CONSOLE_EMAIL_BACKEND
    )

_delivery_required = (
    (os.environ.get("EMAIL_DELIVERY_REQUIRED") or "").strip().lower()
)
EMAIL_DELIVERY_REQUIRED = (
    _delivery_required == "true" if _delivery_required else not DEBUG
)



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [BASE_DIR / 'static']

STORAGES = {
    'default': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = "dashboard"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    }
}

_google_client_id = os.environ.get("GOOGLE_OAUTH_CLIENT_ID")
_google_client_secret = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET")
if _google_client_id and _google_client_secret:
    SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
        "client_id": _google_client_id,
        "secret": _google_client_secret,
        "key": "",
    }


STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "").strip()
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "").strip()
STRIPE_CURRENCY = os.environ.get("STRIPE_CURRENCY", "usd").strip().lower()

