"""
Django settings for E_learning project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local secrets from the .env file (git-ignored — never committed).
# On Railway the variables are injected straight into the environment, so
# this is a harmless no-op there.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-@6zdb&f0f&@$7_z5faa6=4eep@_(a1!c$ylxk_$1fkgd72$$7('
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

# Comma-separated list of hosts allowed to serve this site.
# Includes Railway's default *.up.railway.app domains.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS',
        'localhost,127.0.0.1,.up.railway.app',
    ).split(',')
    if host.strip()
]

# Railway terminates HTTPS at its proxy and forwards the original scheme in
# the X-Forwarded-Proto header. Trusting it lets Django know requests are
# HTTPS, which also fixes CSRF verification on login and registration forms.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'core',
    'courses',
    'accounts',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'E_learning.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'E_learning.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# On Railway we connect to the managed Postgres plugin through the
# DATABASE_URL variable Railway injects automatically. Locally we keep
# using SQLite so `runserver` works as before.

DATABASES = {}
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        conn_max_age=600,
        conn_health_checks=True,
    )
else:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Email (used to send the OTP during registration)
# ---------------------------------------------------------------------------
# Development: the console backend prints every email (including the OTP) to
# the terminal, so no SMTP server is needed locally.
# Production (e.g. Railway): set EMAIL_BACKEND to the SMTP backend (or simply
# remove it) and set the EMAIL_* variables to your provider's values. Nothing
# is hard-coded here — everything comes from environment variables. Empty
# values in .env are treated as "not set".
#
# If no explicit EMAIL_BACKEND is given, one is picked automatically:
#   * in DEBUG (local development) it is always the console backend, which
#     prints every email to the terminal;
#   * in production the SMTP backend is used whenever SMTP credentials
#     (EMAIL_HOST_USER) are configured. If they are not (e.g. a fresh deploy
#     before a mail provider has been added), it falls back to the console
#     backend so registrations still work — the OTP is written to the server
#     logs instead of failing the sign-up outright.
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND")
if not EMAIL_BACKEND:
    if DEBUG or not os.environ.get("EMAIL_HOST_USER"):
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    else:
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST") or "localhost"
EMAIL_PORT = int(os.environ.get("EMAIL_PORT") or "587")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER") or ""
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD") or ""
EMAIL_USE_TLS = (os.environ.get("EMAIL_USE_TLS") or "true").lower() == "true"
# If no explicit From address is given, send from the SMTP account itself —
# many providers (e.g. Gmail) reject emails whose From address does not match
# the authenticated sender.
DEFAULT_FROM_EMAIL = (
    os.environ.get("DEFAULT_FROM_EMAIL")
    or os.environ.get("EMAIL_HOST_USER")
    or "E-Learning <noreply@example.com>"
)


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Extra locations Django's staticfiles finder will look in (served by
# `runserver` in DEBUG and collected via `collectstatic` for production).
STATICFILES_DIRS = [BASE_DIR / 'static']

STORAGES = {
    'default': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth: where users land after login / logout.
LOGIN_REDIRECT_URL = "dashboard"
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

# Let "Continue with Google" redirect straight to Google instead of showing
# allauth's intermediate "click to continue" page.
SOCIALACCOUNT_LOGIN_ON_GET = True

# Custom adapter: keeps "Continue with Google" working even when the Google
# OAuth app is configured both in the Django admin (SocialApp) and via the
# GOOGLE_OAUTH_CLIENT_* environment variables. Without it, that duplicate
# setup makes allauth raise MultipleObjectsReturned -> HTTP 500 on click.
SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountAdapter"

# Google OAuth ("Continue with Google").
# Get OAuth client credentials from the Google Cloud Console:
#   https://console.cloud.google.com/apis/credentials
# Then supply them as environment variables (on Railway add them under
# Variables; locally set them in your terminal, for example):
#   GOOGLE_OAUTH_CLIENT_ID=xxxxx.apps.googleusercontent.com
#   GOOGLE_OAUTH_CLIENT_SECRET=GOCSPX-xxxxx
# Alternative: create the app record in Django admin at
#   /admin/socialaccount/socialapp/  (provider "Google", assigned to a site) —
#   in that case leave the APP block below unset.
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    }
}

_google_client_id = os.environ.get("GOOGLE_OAUTH_CLIENT_ID")
_google_client_secret = os.environ.get("GOOGLE_OAUTH_CLIENT_SECRET")
if _google_client_id and _google_client_secret:
    SOCIALACCOUNT_PROVIDERS["google"]["APP"] = {
        "client_id": _google_client_id,
        "secret": _google_client_secret,
        "key": "",
    }


# Stripe payments ("Buy this course" via Stripe Checkout)
# ---------------------------------------------------------------------------
# All keys are read from the environment ONLY — never hard-code them, never
# commit them. Locally they live in .env (git-ignored); on Railway add them
# under Variables. The keys are used purely server-side; the hosted Checkout
# page keeps card details off this server, so the publishable key is never
# sent to the browser either.
#   STRIPE_PUBLISHABLE_KEY=pk_test_...
#   STRIPE_SECRET_KEY=sk_test_...
#   STRIPE_WEBHOOK_SECRET=whsec_...     (from Stripe > Developers > Webhooks)
# Switch the pk_test_/sk_test_ values for pk_live_/sk_live_ to take real money.
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "").strip()
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "").strip()
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "").strip()
STRIPE_CURRENCY = os.environ.get("STRIPE_CURRENCY", "usd").strip().lower()

